version: '3.8'

services:
  kidschat:
    build: .
    ports:
      - "15000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server/server.py
      - PROXY_PREFIX=/  # Add this if the app is not at root URL
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
