version: '3.8'
services:
  server:
    build: .
    ports:
      - "5000:5000"
      - "40000-49999:40000-49999/udp"
      - "40000-49999:40000-49999/tcp"
    environment:
      - PORT=5000
      - ANNOUNCED_IP=0.0.0.0  # Replace with your actual host IP
    volumes:
      - ./server-new:/app/server-new
      - ./client:/app/client
    networks:
      - webrtc_network

  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    networks:
      - webrtc_network
    depends_on:
      - server

networks:
  webrtc_network:
    driver: bridge
