version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"  # HTTPS
      - "80:80"    # HTTP (optional, for redirects)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kidschat
    restart: unless-stopped

  kidschat:
    build: .
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server/server.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
