version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "40000-40100:40000-40100/udp"
      - "40000-40100:40000-40100/tcp"
    environment:
      - PORT=5000
      - ANNOUNCED_IP=0.0.0.0
      - VIRTUAL_HOST=voicechat.ibnsina.cc
      - LETSENCRYPT_HOST=voicechat.ibnsina.cc
    volumes:
      - ./server-new:/app/server-new
      - ./client:/app/client
    networks:
      - webrtc_network

networks:
  webrtc_network:
    driver: bridge
