FROM node:18-alpine

WORKDIR /app/client

# Install Python, pip, and other build dependencies
RUN apk add --no-cache python3 py3-pip make g++ gcc linux-headers python3-dev musl-dev

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy client files
COPY client/ .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
