version: '3.8'

services:
  kidschat:
    build: .
    ports:
      - "15000:5000"
    environment:
      - NODE_ENV=production
      - ANNOUNCED_IP=192.168.68.61
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
